Models/Dragons.cs
using System.ComponentModel.DataAnnotations;

namespace midterm_project.Models;

public class Dragons {
    public int DragonId { get; set; }

    [Required]
    public string dragonName { get; set; }

    [Required]
    public string dragonImage { get; set; }

    [Required]
    public string dragonDescription { get; set; }

    [Required]
    public string dragonDetails { get; set; }    
}

Models/ErrorViewModel.cs
namespace midterm_project.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/DragonsController.cs
using midterm_project.Models;
using midterm_project.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace midterm_project.Controllers;

public class DragonsController : Controller
{
    private readonly ILogger<DragonsController> _logger;
    private readonly IDragonsRepository _dragonRepository;

    public DragonsController(ILogger<DragonsController> logger, IDragonsRepository repository)
    {
        _logger = logger;
        _dragonRepository = repository;
    }

    public IActionResult Index() {
        return RedirectToAction("List");
    }

    public IActionResult List()
    {
        return View(_dragonRepository.GetAllDragons());
    }

    public IActionResult Detail(int id)
    {
        var dragon = _dragonRepository.GetDragonById(id);

        if (dragon == null) {
            return RedirectToAction("List");
        }

        return View(dragon);
    }

    [HttpPost]
    public IActionResult Detail(Dragons dragon) 
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        return View(_dragonRepository.UpdateDragon(dragon));
    }

    [HttpGet]
    public IActionResult New() 
    {
        return View();
    }

    [HttpPost]
    public IActionResult New(Dragons dragon) 
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        
        _dragonRepository.CreateDragon(dragon);

        return RedirectToAction("List");
    }

    public IActionResult Delete(int id) 
    {
        _dragonRepository.DeleteDragonById(id);

        return RedirectToAction("List");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using midterm_project.Models;

namespace midterm_project.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Dragons/List.cshtml
@model IEnumerable<midterm_project.Models.Dragons>

@{
    ViewData["Title"] = "Dragons Menu";
}

<div class="text-center">
    <h1 class="display-4">Adoption List</h1>
    @foreach (var dragon in Model)
    {
        <h2>@dragon.dragonName - $@dragon.dragonDetails</h2>
        <p>@dragon.dragonDescription</p>
        <a class="btn btn-sm btn-secondary mb-3"
            asp-controller="Dragons" asp-action="Detail" asp-route-id="@dragon.DragonId" >
            View / Edit Dragon
        </a>
        <a class="btn btn-sm btn-danger mb-3 ml-3"
            asp-controller="Dragons" asp-action="Delete" asp-route-id="@dragon.DragonId">
            Delete Dragon
        </a>
    }

    <div>
        <a class="btn btn-primary mt-3 clearfix" asp-controller="Dragons" asp-action="New">Create New</a>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - midterm_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/midterm_project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">midterm_project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - midterm_project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>